### ISSUE TITLE
Please do an FSharp.Core 5.0 compatible release

### ISSUE THREAD

**Issue by kodfodrasz** [vbfox/ColoredPrintf#3]
Greetings!

With .Net 5.0/F# 5.0 out FSharp.Core 5.0.0 has also been released.
When using ColoredPrintf from a project using the version above nuget warnings are issued (but otherwise working correctly)

`NU1608`	`Detected package version outside of dependency constraint: BlackFox.ColoredPrintf 1.0.3 requires FSharp.Core (>= 4.2.3 && < 5.0.0) but version FSharp.Core 5.0.0 was resolved.`

Please provide a newer release where this constraint is loosened/adjusted.

Thank you!

**Comment by anthony-mi** [comment]
@vbfox

**Comment by vbfox** [comment]
👋🏼  Version 1.0.5 is now published and works with .NET 5.0/FSharp.Core 5.0
